module.exports = {
  LOAD_SCHEDULES: 'LOAD_SCHEDULES',
  PLAY_ATTACHMENT: 'PLAY_ATTACHMENT',
  PLAY_PAUSE_ATTACHMENT: 'PLAY_PAUSE_ATTACHMENT',
  CURRENT_ATTACHMENT_TIME: 'CURRENT_ATTACHMENT_TIME',
  PREVIOUS_ATTACHMENT: 'PREVIOUS_ATTACHMENT',
  NEXT_ATTACHMENT: 'NEXT_ATTACHMENT',
  SELECT_PLAN: 'SELECT_PLAN',
  REPEAT_ATTACHMENT: 'REPEAT_ATTACHMENT',
  ATTACHMENT_ENDED: 'ATTACHMENT_ENDED',
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER',
};
