module.exports = {
  LOAD_SCHEDULES: 'LOAD_SCHEDULES',
  PLAY_ATTACHMENT: 'PLAY_ATTACHMENT',
  PLAY_PAUSE_ATTACHMENT: 'PLAY_PAUSE_ATTACHMENT',
  CURRENT_ATTACHMENT_TIME: 'CURRENT_ATTACHMENT_TIME',
  PREVIOUS_ATTACHMENT: 'PREVIOUS_ATTACHMENT',
  NEXT_ATTACHMENT: 'NEXT_ATTACHMENT',
  SELECT_PLAN: 'SELECT_PLAN',
};
