module.exports = {
  LOAD_SCHEDULES: 'LOAD_SCHEDULES',
  PLAY_ATTACHMENT: 'PLAY_ATTACHMENT',
  PLAY_PAUSE_ATTACHMENT: 'PLAY_PAUSE_ATTACHMENT',
  CURRENT_ATTACHMENT_TIME: 'CURRENT_ATTACHMENT_TIME',
};
